package com.tkylin.jdfx.db.model;

import java.util.Date;

public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.author_id
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    private String authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.index_image
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    private String indexImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.imghost
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    private String imghost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.like_num
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    private Integer likeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.pageView
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    private Integer pageview;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.pin
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    private String pin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.publish_time
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    private Date publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.type
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.type_id
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.type_name
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.union_id
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    private String unionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.video_flag
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    private Integer videoFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.summary
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.comment_num
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    private Integer commentNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.banner
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    private String banner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.tags
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.create_time
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.update_time
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.status
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.description
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.author_id
     *
     * @return the value of article.author_id
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public String getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.author_id
     *
     * @param authorId the value for article.author_id
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public void setAuthorId(String authorId) {
        this.authorId = authorId == null ? null : authorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.index_image
     *
     * @return the value of article.index_image
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public String getIndexImage() {
        return indexImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.index_image
     *
     * @param indexImage the value for article.index_image
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public void setIndexImage(String indexImage) {
        this.indexImage = indexImage == null ? null : indexImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.imghost
     *
     * @return the value of article.imghost
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public String getImghost() {
        return imghost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.imghost
     *
     * @param imghost the value for article.imghost
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public void setImghost(String imghost) {
        this.imghost = imghost == null ? null : imghost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.like_num
     *
     * @return the value of article.like_num
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public Integer getLikeNum() {
        return likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.like_num
     *
     * @param likeNum the value for article.like_num
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public void setLikeNum(Integer likeNum) {
        this.likeNum = likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.pageView
     *
     * @return the value of article.pageView
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public Integer getPageview() {
        return pageview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.pageView
     *
     * @param pageview the value for article.pageView
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public void setPageview(Integer pageview) {
        this.pageview = pageview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.pin
     *
     * @return the value of article.pin
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public String getPin() {
        return pin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.pin
     *
     * @param pin the value for article.pin
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public void setPin(String pin) {
        this.pin = pin == null ? null : pin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.publish_time
     *
     * @return the value of article.publish_time
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.publish_time
     *
     * @param publishTime the value for article.publish_time
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.type
     *
     * @return the value of article.type
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.type
     *
     * @param type the value for article.type
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.type_id
     *
     * @return the value of article.type_id
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.type_id
     *
     * @param typeId the value for article.type_id
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.type_name
     *
     * @return the value of article.type_name
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.type_name
     *
     * @param typeName the value for article.type_name
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.union_id
     *
     * @return the value of article.union_id
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.union_id
     *
     * @param unionId the value for article.union_id
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId == null ? null : unionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.video_flag
     *
     * @return the value of article.video_flag
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public Integer getVideoFlag() {
        return videoFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.video_flag
     *
     * @param videoFlag the value for article.video_flag
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public void setVideoFlag(Integer videoFlag) {
        this.videoFlag = videoFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.summary
     *
     * @return the value of article.summary
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.summary
     *
     * @param summary the value for article.summary
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.comment_num
     *
     * @return the value of article.comment_num
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public Integer getCommentNum() {
        return commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.comment_num
     *
     * @param commentNum the value for article.comment_num
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public void setCommentNum(Integer commentNum) {
        this.commentNum = commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.banner
     *
     * @return the value of article.banner
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public String getBanner() {
        return banner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.banner
     *
     * @param banner the value for article.banner
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public void setBanner(String banner) {
        this.banner = banner == null ? null : banner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.tags
     *
     * @return the value of article.tags
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.tags
     *
     * @param tags the value for article.tags
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.create_time
     *
     * @return the value of article.create_time
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.create_time
     *
     * @param createTime the value for article.create_time
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.update_time
     *
     * @return the value of article.update_time
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.update_time
     *
     * @param updateTime the value for article.update_time
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.status
     *
     * @return the value of article.status
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.status
     *
     * @param status the value for article.status
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.description
     *
     * @return the value of article.description
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.description
     *
     * @param description the value for article.description
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}