package com.tkylin.jdfx.db.model;

public class ArticleType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_type.id
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_type.name
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_type.test_id
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    private String test_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_type.id
     *
     * @return the value of article_type.id
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_type.id
     *
     * @param id the value for article_type.id
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_type.name
     *
     * @return the value of article_type.name
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_type.name
     *
     * @param name the value for article_type.name
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_type.test_id
     *
     * @return the value of article_type.test_id
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public String getTest_id() {
        return test_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_type.test_id
     *
     * @param test_id the value for article_type.test_id
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public void setTest_id(String test_id) {
        this.test_id = test_id == null ? null : test_id.trim();
    }
}