package com.tkylin.jdfx.db.model;

import java.util.Date;

public class Author {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.author_id
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    private String author_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.author_name
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    private String author_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.author_pic
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    private String author_pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.author_sign
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    private String author_sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.author_synopsis
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    private String author_synopsis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.author_url
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    private String author_url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.author_level
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    private Integer author_level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.author_article_num
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    private Integer author_article_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.goods_nums
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    private Integer goods_nums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.list_nums
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    private Integer list_nums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.follow_nums
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    private Integer follow_nums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.has_followed
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    private Integer has_followed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.signature
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    private String signature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.create_time
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.update_time
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    private Date update_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.status
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.author_id
     *
     * @return the value of author.author_id
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public String getAuthor_id() {
        return author_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.author_id
     *
     * @param author_id the value for author.author_id
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public void setAuthor_id(String author_id) {
        this.author_id = author_id == null ? null : author_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.author_name
     *
     * @return the value of author.author_name
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public String getAuthor_name() {
        return author_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.author_name
     *
     * @param author_name the value for author.author_name
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public void setAuthor_name(String author_name) {
        this.author_name = author_name == null ? null : author_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.author_pic
     *
     * @return the value of author.author_pic
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public String getAuthor_pic() {
        return author_pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.author_pic
     *
     * @param author_pic the value for author.author_pic
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public void setAuthor_pic(String author_pic) {
        this.author_pic = author_pic == null ? null : author_pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.author_sign
     *
     * @return the value of author.author_sign
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public String getAuthor_sign() {
        return author_sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.author_sign
     *
     * @param author_sign the value for author.author_sign
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public void setAuthor_sign(String author_sign) {
        this.author_sign = author_sign == null ? null : author_sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.author_synopsis
     *
     * @return the value of author.author_synopsis
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public String getAuthor_synopsis() {
        return author_synopsis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.author_synopsis
     *
     * @param author_synopsis the value for author.author_synopsis
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public void setAuthor_synopsis(String author_synopsis) {
        this.author_synopsis = author_synopsis == null ? null : author_synopsis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.author_url
     *
     * @return the value of author.author_url
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public String getAuthor_url() {
        return author_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.author_url
     *
     * @param author_url the value for author.author_url
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public void setAuthor_url(String author_url) {
        this.author_url = author_url == null ? null : author_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.author_level
     *
     * @return the value of author.author_level
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public Integer getAuthor_level() {
        return author_level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.author_level
     *
     * @param author_level the value for author.author_level
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public void setAuthor_level(Integer author_level) {
        this.author_level = author_level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.author_article_num
     *
     * @return the value of author.author_article_num
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public Integer getAuthor_article_num() {
        return author_article_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.author_article_num
     *
     * @param author_article_num the value for author.author_article_num
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public void setAuthor_article_num(Integer author_article_num) {
        this.author_article_num = author_article_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.goods_nums
     *
     * @return the value of author.goods_nums
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public Integer getGoods_nums() {
        return goods_nums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.goods_nums
     *
     * @param goods_nums the value for author.goods_nums
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public void setGoods_nums(Integer goods_nums) {
        this.goods_nums = goods_nums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.list_nums
     *
     * @return the value of author.list_nums
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public Integer getList_nums() {
        return list_nums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.list_nums
     *
     * @param list_nums the value for author.list_nums
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public void setList_nums(Integer list_nums) {
        this.list_nums = list_nums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.follow_nums
     *
     * @return the value of author.follow_nums
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public Integer getFollow_nums() {
        return follow_nums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.follow_nums
     *
     * @param follow_nums the value for author.follow_nums
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public void setFollow_nums(Integer follow_nums) {
        this.follow_nums = follow_nums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.has_followed
     *
     * @return the value of author.has_followed
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public Integer getHas_followed() {
        return has_followed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.has_followed
     *
     * @param has_followed the value for author.has_followed
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public void setHas_followed(Integer has_followed) {
        this.has_followed = has_followed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.signature
     *
     * @return the value of author.signature
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.signature
     *
     * @param signature the value for author.signature
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.create_time
     *
     * @return the value of author.create_time
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.create_time
     *
     * @param create_time the value for author.create_time
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.update_time
     *
     * @return the value of author.update_time
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.update_time
     *
     * @param update_time the value for author.update_time
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.status
     *
     * @return the value of author.status
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.status
     *
     * @param status the value for author.status
     *
     * @mbg.generated Sat Mar 11 00:07:13 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}