package com.tkylin.jdfx.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FindExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table find
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table find
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table find
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public FindExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table find
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFindIdIsNull() {
            addCriterion("find_id is null");
            return (Criteria) this;
        }

        public Criteria andFindIdIsNotNull() {
            addCriterion("find_id is not null");
            return (Criteria) this;
        }

        public Criteria andFindIdEqualTo(Long value) {
            addCriterion("find_id =", value, "findId");
            return (Criteria) this;
        }

        public Criteria andFindIdNotEqualTo(Long value) {
            addCriterion("find_id <>", value, "findId");
            return (Criteria) this;
        }

        public Criteria andFindIdGreaterThan(Long value) {
            addCriterion("find_id >", value, "findId");
            return (Criteria) this;
        }

        public Criteria andFindIdGreaterThanOrEqualTo(Long value) {
            addCriterion("find_id >=", value, "findId");
            return (Criteria) this;
        }

        public Criteria andFindIdLessThan(Long value) {
            addCriterion("find_id <", value, "findId");
            return (Criteria) this;
        }

        public Criteria andFindIdLessThanOrEqualTo(Long value) {
            addCriterion("find_id <=", value, "findId");
            return (Criteria) this;
        }

        public Criteria andFindIdIn(List<Long> values) {
            addCriterion("find_id in", values, "findId");
            return (Criteria) this;
        }

        public Criteria andFindIdNotIn(List<Long> values) {
            addCriterion("find_id not in", values, "findId");
            return (Criteria) this;
        }

        public Criteria andFindIdBetween(Long value1, Long value2) {
            addCriterion("find_id between", value1, value2, "findId");
            return (Criteria) this;
        }

        public Criteria andFindIdNotBetween(Long value1, Long value2) {
            addCriterion("find_id not between", value1, value2, "findId");
            return (Criteria) this;
        }

        public Criteria andArticleidIsNull() {
            addCriterion("articleId is null");
            return (Criteria) this;
        }

        public Criteria andArticleidIsNotNull() {
            addCriterion("articleId is not null");
            return (Criteria) this;
        }

        public Criteria andArticleidEqualTo(String value) {
            addCriterion("articleId =", value, "articleid");
            return (Criteria) this;
        }

        public Criteria andArticleidNotEqualTo(String value) {
            addCriterion("articleId <>", value, "articleid");
            return (Criteria) this;
        }

        public Criteria andArticleidGreaterThan(String value) {
            addCriterion("articleId >", value, "articleid");
            return (Criteria) this;
        }

        public Criteria andArticleidGreaterThanOrEqualTo(String value) {
            addCriterion("articleId >=", value, "articleid");
            return (Criteria) this;
        }

        public Criteria andArticleidLessThan(String value) {
            addCriterion("articleId <", value, "articleid");
            return (Criteria) this;
        }

        public Criteria andArticleidLessThanOrEqualTo(String value) {
            addCriterion("articleId <=", value, "articleid");
            return (Criteria) this;
        }

        public Criteria andArticleidLike(String value) {
            addCriterion("articleId like", value, "articleid");
            return (Criteria) this;
        }

        public Criteria andArticleidNotLike(String value) {
            addCriterion("articleId not like", value, "articleid");
            return (Criteria) this;
        }

        public Criteria andArticleidIn(List<String> values) {
            addCriterion("articleId in", values, "articleid");
            return (Criteria) this;
        }

        public Criteria andArticleidNotIn(List<String> values) {
            addCriterion("articleId not in", values, "articleid");
            return (Criteria) this;
        }

        public Criteria andArticleidBetween(String value1, String value2) {
            addCriterion("articleId between", value1, value2, "articleid");
            return (Criteria) this;
        }

        public Criteria andArticleidNotBetween(String value1, String value2) {
            addCriterion("articleId not between", value1, value2, "articleid");
            return (Criteria) this;
        }

        public Criteria andAuthornameIsNull() {
            addCriterion("authorName is null");
            return (Criteria) this;
        }

        public Criteria andAuthornameIsNotNull() {
            addCriterion("authorName is not null");
            return (Criteria) this;
        }

        public Criteria andAuthornameEqualTo(String value) {
            addCriterion("authorName =", value, "authorname");
            return (Criteria) this;
        }

        public Criteria andAuthornameNotEqualTo(String value) {
            addCriterion("authorName <>", value, "authorname");
            return (Criteria) this;
        }

        public Criteria andAuthornameGreaterThan(String value) {
            addCriterion("authorName >", value, "authorname");
            return (Criteria) this;
        }

        public Criteria andAuthornameGreaterThanOrEqualTo(String value) {
            addCriterion("authorName >=", value, "authorname");
            return (Criteria) this;
        }

        public Criteria andAuthornameLessThan(String value) {
            addCriterion("authorName <", value, "authorname");
            return (Criteria) this;
        }

        public Criteria andAuthornameLessThanOrEqualTo(String value) {
            addCriterion("authorName <=", value, "authorname");
            return (Criteria) this;
        }

        public Criteria andAuthornameLike(String value) {
            addCriterion("authorName like", value, "authorname");
            return (Criteria) this;
        }

        public Criteria andAuthornameNotLike(String value) {
            addCriterion("authorName not like", value, "authorname");
            return (Criteria) this;
        }

        public Criteria andAuthornameIn(List<String> values) {
            addCriterion("authorName in", values, "authorname");
            return (Criteria) this;
        }

        public Criteria andAuthornameNotIn(List<String> values) {
            addCriterion("authorName not in", values, "authorname");
            return (Criteria) this;
        }

        public Criteria andAuthornameBetween(String value1, String value2) {
            addCriterion("authorName between", value1, value2, "authorname");
            return (Criteria) this;
        }

        public Criteria andAuthornameNotBetween(String value1, String value2) {
            addCriterion("authorName not between", value1, value2, "authorname");
            return (Criteria) this;
        }

        public Criteria andAuthorpicIsNull() {
            addCriterion("authorPic is null");
            return (Criteria) this;
        }

        public Criteria andAuthorpicIsNotNull() {
            addCriterion("authorPic is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorpicEqualTo(String value) {
            addCriterion("authorPic =", value, "authorpic");
            return (Criteria) this;
        }

        public Criteria andAuthorpicNotEqualTo(String value) {
            addCriterion("authorPic <>", value, "authorpic");
            return (Criteria) this;
        }

        public Criteria andAuthorpicGreaterThan(String value) {
            addCriterion("authorPic >", value, "authorpic");
            return (Criteria) this;
        }

        public Criteria andAuthorpicGreaterThanOrEqualTo(String value) {
            addCriterion("authorPic >=", value, "authorpic");
            return (Criteria) this;
        }

        public Criteria andAuthorpicLessThan(String value) {
            addCriterion("authorPic <", value, "authorpic");
            return (Criteria) this;
        }

        public Criteria andAuthorpicLessThanOrEqualTo(String value) {
            addCriterion("authorPic <=", value, "authorpic");
            return (Criteria) this;
        }

        public Criteria andAuthorpicLike(String value) {
            addCriterion("authorPic like", value, "authorpic");
            return (Criteria) this;
        }

        public Criteria andAuthorpicNotLike(String value) {
            addCriterion("authorPic not like", value, "authorpic");
            return (Criteria) this;
        }

        public Criteria andAuthorpicIn(List<String> values) {
            addCriterion("authorPic in", values, "authorpic");
            return (Criteria) this;
        }

        public Criteria andAuthorpicNotIn(List<String> values) {
            addCriterion("authorPic not in", values, "authorpic");
            return (Criteria) this;
        }

        public Criteria andAuthorpicBetween(String value1, String value2) {
            addCriterion("authorPic between", value1, value2, "authorpic");
            return (Criteria) this;
        }

        public Criteria andAuthorpicNotBetween(String value1, String value2) {
            addCriterion("authorPic not between", value1, value2, "authorpic");
            return (Criteria) this;
        }

        public Criteria andIndeximageIsNull() {
            addCriterion("indexImage is null");
            return (Criteria) this;
        }

        public Criteria andIndeximageIsNotNull() {
            addCriterion("indexImage is not null");
            return (Criteria) this;
        }

        public Criteria andIndeximageEqualTo(String value) {
            addCriterion("indexImage =", value, "indeximage");
            return (Criteria) this;
        }

        public Criteria andIndeximageNotEqualTo(String value) {
            addCriterion("indexImage <>", value, "indeximage");
            return (Criteria) this;
        }

        public Criteria andIndeximageGreaterThan(String value) {
            addCriterion("indexImage >", value, "indeximage");
            return (Criteria) this;
        }

        public Criteria andIndeximageGreaterThanOrEqualTo(String value) {
            addCriterion("indexImage >=", value, "indeximage");
            return (Criteria) this;
        }

        public Criteria andIndeximageLessThan(String value) {
            addCriterion("indexImage <", value, "indeximage");
            return (Criteria) this;
        }

        public Criteria andIndeximageLessThanOrEqualTo(String value) {
            addCriterion("indexImage <=", value, "indeximage");
            return (Criteria) this;
        }

        public Criteria andIndeximageLike(String value) {
            addCriterion("indexImage like", value, "indeximage");
            return (Criteria) this;
        }

        public Criteria andIndeximageNotLike(String value) {
            addCriterion("indexImage not like", value, "indeximage");
            return (Criteria) this;
        }

        public Criteria andIndeximageIn(List<String> values) {
            addCriterion("indexImage in", values, "indeximage");
            return (Criteria) this;
        }

        public Criteria andIndeximageNotIn(List<String> values) {
            addCriterion("indexImage not in", values, "indeximage");
            return (Criteria) this;
        }

        public Criteria andIndeximageBetween(String value1, String value2) {
            addCriterion("indexImage between", value1, value2, "indeximage");
            return (Criteria) this;
        }

        public Criteria andIndeximageNotBetween(String value1, String value2) {
            addCriterion("indexImage not between", value1, value2, "indeximage");
            return (Criteria) this;
        }

        public Criteria andPageviewIsNull() {
            addCriterion("pageView is null");
            return (Criteria) this;
        }

        public Criteria andPageviewIsNotNull() {
            addCriterion("pageView is not null");
            return (Criteria) this;
        }

        public Criteria andPageviewEqualTo(Integer value) {
            addCriterion("pageView =", value, "pageview");
            return (Criteria) this;
        }

        public Criteria andPageviewNotEqualTo(Integer value) {
            addCriterion("pageView <>", value, "pageview");
            return (Criteria) this;
        }

        public Criteria andPageviewGreaterThan(Integer value) {
            addCriterion("pageView >", value, "pageview");
            return (Criteria) this;
        }

        public Criteria andPageviewGreaterThanOrEqualTo(Integer value) {
            addCriterion("pageView >=", value, "pageview");
            return (Criteria) this;
        }

        public Criteria andPageviewLessThan(Integer value) {
            addCriterion("pageView <", value, "pageview");
            return (Criteria) this;
        }

        public Criteria andPageviewLessThanOrEqualTo(Integer value) {
            addCriterion("pageView <=", value, "pageview");
            return (Criteria) this;
        }

        public Criteria andPageviewIn(List<Integer> values) {
            addCriterion("pageView in", values, "pageview");
            return (Criteria) this;
        }

        public Criteria andPageviewNotIn(List<Integer> values) {
            addCriterion("pageView not in", values, "pageview");
            return (Criteria) this;
        }

        public Criteria andPageviewBetween(Integer value1, Integer value2) {
            addCriterion("pageView between", value1, value2, "pageview");
            return (Criteria) this;
        }

        public Criteria andPageviewNotBetween(Integer value1, Integer value2) {
            addCriterion("pageView not between", value1, value2, "pageview");
            return (Criteria) this;
        }

        public Criteria andPublishtimeIsNull() {
            addCriterion("publishTime is null");
            return (Criteria) this;
        }

        public Criteria andPublishtimeIsNotNull() {
            addCriterion("publishTime is not null");
            return (Criteria) this;
        }

        public Criteria andPublishtimeEqualTo(Date value) {
            addCriterion("publishTime =", value, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeNotEqualTo(Date value) {
            addCriterion("publishTime <>", value, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeGreaterThan(Date value) {
            addCriterion("publishTime >", value, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("publishTime >=", value, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeLessThan(Date value) {
            addCriterion("publishTime <", value, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeLessThanOrEqualTo(Date value) {
            addCriterion("publishTime <=", value, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeIn(List<Date> values) {
            addCriterion("publishTime in", values, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeNotIn(List<Date> values) {
            addCriterion("publishTime not in", values, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeBetween(Date value1, Date value2) {
            addCriterion("publishTime between", value1, value2, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeNotBetween(Date value1, Date value2) {
            addCriterion("publishTime not between", value1, value2, "publishtime");
            return (Criteria) this;
        }

        public Criteria andShowtimeIsNull() {
            addCriterion("showTime is null");
            return (Criteria) this;
        }

        public Criteria andShowtimeIsNotNull() {
            addCriterion("showTime is not null");
            return (Criteria) this;
        }

        public Criteria andShowtimeEqualTo(String value) {
            addCriterion("showTime =", value, "showtime");
            return (Criteria) this;
        }

        public Criteria andShowtimeNotEqualTo(String value) {
            addCriterion("showTime <>", value, "showtime");
            return (Criteria) this;
        }

        public Criteria andShowtimeGreaterThan(String value) {
            addCriterion("showTime >", value, "showtime");
            return (Criteria) this;
        }

        public Criteria andShowtimeGreaterThanOrEqualTo(String value) {
            addCriterion("showTime >=", value, "showtime");
            return (Criteria) this;
        }

        public Criteria andShowtimeLessThan(String value) {
            addCriterion("showTime <", value, "showtime");
            return (Criteria) this;
        }

        public Criteria andShowtimeLessThanOrEqualTo(String value) {
            addCriterion("showTime <=", value, "showtime");
            return (Criteria) this;
        }

        public Criteria andShowtimeLike(String value) {
            addCriterion("showTime like", value, "showtime");
            return (Criteria) this;
        }

        public Criteria andShowtimeNotLike(String value) {
            addCriterion("showTime not like", value, "showtime");
            return (Criteria) this;
        }

        public Criteria andShowtimeIn(List<String> values) {
            addCriterion("showTime in", values, "showtime");
            return (Criteria) this;
        }

        public Criteria andShowtimeNotIn(List<String> values) {
            addCriterion("showTime not in", values, "showtime");
            return (Criteria) this;
        }

        public Criteria andShowtimeBetween(String value1, String value2) {
            addCriterion("showTime between", value1, value2, "showtime");
            return (Criteria) this;
        }

        public Criteria andShowtimeNotBetween(String value1, String value2) {
            addCriterion("showTime not between", value1, value2, "showtime");
            return (Criteria) this;
        }

        public Criteria andSrvIsNull() {
            addCriterion("srv is null");
            return (Criteria) this;
        }

        public Criteria andSrvIsNotNull() {
            addCriterion("srv is not null");
            return (Criteria) this;
        }

        public Criteria andSrvEqualTo(String value) {
            addCriterion("srv =", value, "srv");
            return (Criteria) this;
        }

        public Criteria andSrvNotEqualTo(String value) {
            addCriterion("srv <>", value, "srv");
            return (Criteria) this;
        }

        public Criteria andSrvGreaterThan(String value) {
            addCriterion("srv >", value, "srv");
            return (Criteria) this;
        }

        public Criteria andSrvGreaterThanOrEqualTo(String value) {
            addCriterion("srv >=", value, "srv");
            return (Criteria) this;
        }

        public Criteria andSrvLessThan(String value) {
            addCriterion("srv <", value, "srv");
            return (Criteria) this;
        }

        public Criteria andSrvLessThanOrEqualTo(String value) {
            addCriterion("srv <=", value, "srv");
            return (Criteria) this;
        }

        public Criteria andSrvLike(String value) {
            addCriterion("srv like", value, "srv");
            return (Criteria) this;
        }

        public Criteria andSrvNotLike(String value) {
            addCriterion("srv not like", value, "srv");
            return (Criteria) this;
        }

        public Criteria andSrvIn(List<String> values) {
            addCriterion("srv in", values, "srv");
            return (Criteria) this;
        }

        public Criteria andSrvNotIn(List<String> values) {
            addCriterion("srv not in", values, "srv");
            return (Criteria) this;
        }

        public Criteria andSrvBetween(String value1, String value2) {
            addCriterion("srv between", value1, value2, "srv");
            return (Criteria) this;
        }

        public Criteria andSrvNotBetween(String value1, String value2) {
            addCriterion("srv not between", value1, value2, "srv");
            return (Criteria) this;
        }

        public Criteria andSummaryIsNull() {
            addCriterion("summary is null");
            return (Criteria) this;
        }

        public Criteria andSummaryIsNotNull() {
            addCriterion("summary is not null");
            return (Criteria) this;
        }

        public Criteria andSummaryEqualTo(String value) {
            addCriterion("summary =", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotEqualTo(String value) {
            addCriterion("summary <>", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryGreaterThan(String value) {
            addCriterion("summary >", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryGreaterThanOrEqualTo(String value) {
            addCriterion("summary >=", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLessThan(String value) {
            addCriterion("summary <", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLessThanOrEqualTo(String value) {
            addCriterion("summary <=", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLike(String value) {
            addCriterion("summary like", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotLike(String value) {
            addCriterion("summary not like", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryIn(List<String> values) {
            addCriterion("summary in", values, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotIn(List<String> values) {
            addCriterion("summary not in", values, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryBetween(String value1, String value2) {
            addCriterion("summary between", value1, value2, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotBetween(String value1, String value2) {
            addCriterion("summary not between", value1, value2, "summary");
            return (Criteria) this;
        }

        public Criteria andTagslistIsNull() {
            addCriterion("tagsList is null");
            return (Criteria) this;
        }

        public Criteria andTagslistIsNotNull() {
            addCriterion("tagsList is not null");
            return (Criteria) this;
        }

        public Criteria andTagslistEqualTo(String value) {
            addCriterion("tagsList =", value, "tagslist");
            return (Criteria) this;
        }

        public Criteria andTagslistNotEqualTo(String value) {
            addCriterion("tagsList <>", value, "tagslist");
            return (Criteria) this;
        }

        public Criteria andTagslistGreaterThan(String value) {
            addCriterion("tagsList >", value, "tagslist");
            return (Criteria) this;
        }

        public Criteria andTagslistGreaterThanOrEqualTo(String value) {
            addCriterion("tagsList >=", value, "tagslist");
            return (Criteria) this;
        }

        public Criteria andTagslistLessThan(String value) {
            addCriterion("tagsList <", value, "tagslist");
            return (Criteria) this;
        }

        public Criteria andTagslistLessThanOrEqualTo(String value) {
            addCriterion("tagsList <=", value, "tagslist");
            return (Criteria) this;
        }

        public Criteria andTagslistLike(String value) {
            addCriterion("tagsList like", value, "tagslist");
            return (Criteria) this;
        }

        public Criteria andTagslistNotLike(String value) {
            addCriterion("tagsList not like", value, "tagslist");
            return (Criteria) this;
        }

        public Criteria andTagslistIn(List<String> values) {
            addCriterion("tagsList in", values, "tagslist");
            return (Criteria) this;
        }

        public Criteria andTagslistNotIn(List<String> values) {
            addCriterion("tagsList not in", values, "tagslist");
            return (Criteria) this;
        }

        public Criteria andTagslistBetween(String value1, String value2) {
            addCriterion("tagsList between", value1, value2, "tagslist");
            return (Criteria) this;
        }

        public Criteria andTagslistNotBetween(String value1, String value2) {
            addCriterion("tagsList not between", value1, value2, "tagslist");
            return (Criteria) this;
        }

        public Criteria andTestidIsNull() {
            addCriterion("testId is null");
            return (Criteria) this;
        }

        public Criteria andTestidIsNotNull() {
            addCriterion("testId is not null");
            return (Criteria) this;
        }

        public Criteria andTestidEqualTo(String value) {
            addCriterion("testId =", value, "testid");
            return (Criteria) this;
        }

        public Criteria andTestidNotEqualTo(String value) {
            addCriterion("testId <>", value, "testid");
            return (Criteria) this;
        }

        public Criteria andTestidGreaterThan(String value) {
            addCriterion("testId >", value, "testid");
            return (Criteria) this;
        }

        public Criteria andTestidGreaterThanOrEqualTo(String value) {
            addCriterion("testId >=", value, "testid");
            return (Criteria) this;
        }

        public Criteria andTestidLessThan(String value) {
            addCriterion("testId <", value, "testid");
            return (Criteria) this;
        }

        public Criteria andTestidLessThanOrEqualTo(String value) {
            addCriterion("testId <=", value, "testid");
            return (Criteria) this;
        }

        public Criteria andTestidLike(String value) {
            addCriterion("testId like", value, "testid");
            return (Criteria) this;
        }

        public Criteria andTestidNotLike(String value) {
            addCriterion("testId not like", value, "testid");
            return (Criteria) this;
        }

        public Criteria andTestidIn(List<String> values) {
            addCriterion("testId in", values, "testid");
            return (Criteria) this;
        }

        public Criteria andTestidNotIn(List<String> values) {
            addCriterion("testId not in", values, "testid");
            return (Criteria) this;
        }

        public Criteria andTestidBetween(String value1, String value2) {
            addCriterion("testId between", value1, value2, "testid");
            return (Criteria) this;
        }

        public Criteria andTestidNotBetween(String value1, String value2) {
            addCriterion("testId not between", value1, value2, "testid");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTopIsNull() {
            addCriterion("top is null");
            return (Criteria) this;
        }

        public Criteria andTopIsNotNull() {
            addCriterion("top is not null");
            return (Criteria) this;
        }

        public Criteria andTopEqualTo(Integer value) {
            addCriterion("top =", value, "top");
            return (Criteria) this;
        }

        public Criteria andTopNotEqualTo(Integer value) {
            addCriterion("top <>", value, "top");
            return (Criteria) this;
        }

        public Criteria andTopGreaterThan(Integer value) {
            addCriterion("top >", value, "top");
            return (Criteria) this;
        }

        public Criteria andTopGreaterThanOrEqualTo(Integer value) {
            addCriterion("top >=", value, "top");
            return (Criteria) this;
        }

        public Criteria andTopLessThan(Integer value) {
            addCriterion("top <", value, "top");
            return (Criteria) this;
        }

        public Criteria andTopLessThanOrEqualTo(Integer value) {
            addCriterion("top <=", value, "top");
            return (Criteria) this;
        }

        public Criteria andTopIn(List<Integer> values) {
            addCriterion("top in", values, "top");
            return (Criteria) this;
        }

        public Criteria andTopNotIn(List<Integer> values) {
            addCriterion("top not in", values, "top");
            return (Criteria) this;
        }

        public Criteria andTopBetween(Integer value1, Integer value2) {
            addCriterion("top between", value1, value2, "top");
            return (Criteria) this;
        }

        public Criteria andTopNotBetween(Integer value1, Integer value2) {
            addCriterion("top not between", value1, value2, "top");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andVideoflagIsNull() {
            addCriterion("videoFlag is null");
            return (Criteria) this;
        }

        public Criteria andVideoflagIsNotNull() {
            addCriterion("videoFlag is not null");
            return (Criteria) this;
        }

        public Criteria andVideoflagEqualTo(Integer value) {
            addCriterion("videoFlag =", value, "videoflag");
            return (Criteria) this;
        }

        public Criteria andVideoflagNotEqualTo(Integer value) {
            addCriterion("videoFlag <>", value, "videoflag");
            return (Criteria) this;
        }

        public Criteria andVideoflagGreaterThan(Integer value) {
            addCriterion("videoFlag >", value, "videoflag");
            return (Criteria) this;
        }

        public Criteria andVideoflagGreaterThanOrEqualTo(Integer value) {
            addCriterion("videoFlag >=", value, "videoflag");
            return (Criteria) this;
        }

        public Criteria andVideoflagLessThan(Integer value) {
            addCriterion("videoFlag <", value, "videoflag");
            return (Criteria) this;
        }

        public Criteria andVideoflagLessThanOrEqualTo(Integer value) {
            addCriterion("videoFlag <=", value, "videoflag");
            return (Criteria) this;
        }

        public Criteria andVideoflagIn(List<Integer> values) {
            addCriterion("videoFlag in", values, "videoflag");
            return (Criteria) this;
        }

        public Criteria andVideoflagNotIn(List<Integer> values) {
            addCriterion("videoFlag not in", values, "videoflag");
            return (Criteria) this;
        }

        public Criteria andVideoflagBetween(Integer value1, Integer value2) {
            addCriterion("videoFlag between", value1, value2, "videoflag");
            return (Criteria) this;
        }

        public Criteria andVideoflagNotBetween(Integer value1, Integer value2) {
            addCriterion("videoFlag not between", value1, value2, "videoflag");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table find
     *
     * @mbg.generated do_not_delete_during_merge Sat Mar 11 01:21:03 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table find
     *
     * @mbg.generated Sat Mar 11 01:21:03 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}