package com.tkylin.jdfx.db.model;

import java.util.Date;

public class Find {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.find_id
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    private Long findId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.articleId
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    private String articleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.authorName
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    private String authorname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.authorPic
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    private String authorpic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.indexImage
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    private String indeximage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.pageView
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    private Integer pageview;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.publishTime
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    private Date publishtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.showTime
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    private String showtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.srv
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    private String srv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.summary
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.tagsList
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    private String tagslist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.testId
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    private String testid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.title
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.top
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    private Integer top;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.type
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.videoFlag
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    private Integer videoflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.create_time
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.update_time
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find.status
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.find_id
     *
     * @return the value of find.find_id
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public Long getFindId() {
        return findId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.find_id
     *
     * @param findId the value for find.find_id
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public void setFindId(Long findId) {
        this.findId = findId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.articleId
     *
     * @return the value of find.articleId
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public String getArticleid() {
        return articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.articleId
     *
     * @param articleid the value for find.articleId
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public void setArticleid(String articleid) {
        this.articleid = articleid == null ? null : articleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.authorName
     *
     * @return the value of find.authorName
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public String getAuthorname() {
        return authorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.authorName
     *
     * @param authorname the value for find.authorName
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public void setAuthorname(String authorname) {
        this.authorname = authorname == null ? null : authorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.authorPic
     *
     * @return the value of find.authorPic
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public String getAuthorpic() {
        return authorpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.authorPic
     *
     * @param authorpic the value for find.authorPic
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public void setAuthorpic(String authorpic) {
        this.authorpic = authorpic == null ? null : authorpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.indexImage
     *
     * @return the value of find.indexImage
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public String getIndeximage() {
        return indeximage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.indexImage
     *
     * @param indeximage the value for find.indexImage
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public void setIndeximage(String indeximage) {
        this.indeximage = indeximage == null ? null : indeximage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.pageView
     *
     * @return the value of find.pageView
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public Integer getPageview() {
        return pageview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.pageView
     *
     * @param pageview the value for find.pageView
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public void setPageview(Integer pageview) {
        this.pageview = pageview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.publishTime
     *
     * @return the value of find.publishTime
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public Date getPublishtime() {
        return publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.publishTime
     *
     * @param publishtime the value for find.publishTime
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public void setPublishtime(Date publishtime) {
        this.publishtime = publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.showTime
     *
     * @return the value of find.showTime
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public String getShowtime() {
        return showtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.showTime
     *
     * @param showtime the value for find.showTime
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public void setShowtime(String showtime) {
        this.showtime = showtime == null ? null : showtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.srv
     *
     * @return the value of find.srv
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public String getSrv() {
        return srv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.srv
     *
     * @param srv the value for find.srv
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public void setSrv(String srv) {
        this.srv = srv == null ? null : srv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.summary
     *
     * @return the value of find.summary
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.summary
     *
     * @param summary the value for find.summary
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.tagsList
     *
     * @return the value of find.tagsList
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public String getTagslist() {
        return tagslist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.tagsList
     *
     * @param tagslist the value for find.tagsList
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public void setTagslist(String tagslist) {
        this.tagslist = tagslist == null ? null : tagslist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.testId
     *
     * @return the value of find.testId
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public String getTestid() {
        return testid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.testId
     *
     * @param testid the value for find.testId
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public void setTestid(String testid) {
        this.testid = testid == null ? null : testid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.title
     *
     * @return the value of find.title
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.title
     *
     * @param title the value for find.title
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.top
     *
     * @return the value of find.top
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public Integer getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.top
     *
     * @param top the value for find.top
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public void setTop(Integer top) {
        this.top = top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.type
     *
     * @return the value of find.type
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.type
     *
     * @param type the value for find.type
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.videoFlag
     *
     * @return the value of find.videoFlag
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public Integer getVideoflag() {
        return videoflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.videoFlag
     *
     * @param videoflag the value for find.videoFlag
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public void setVideoflag(Integer videoflag) {
        this.videoflag = videoflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.create_time
     *
     * @return the value of find.create_time
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.create_time
     *
     * @param createTime the value for find.create_time
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.update_time
     *
     * @return the value of find.update_time
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.update_time
     *
     * @param updateTime the value for find.update_time
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find.status
     *
     * @return the value of find.status
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find.status
     *
     * @param status the value for find.status
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}