package com.tkylin.jdfx.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GoodsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public GoodsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGoods_idIsNull() {
            addCriterion("goods_id is null");
            return (Criteria) this;
        }

        public Criteria andGoods_idIsNotNull() {
            addCriterion("goods_id is not null");
            return (Criteria) this;
        }

        public Criteria andGoods_idEqualTo(Long value) {
            addCriterion("goods_id =", value, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idNotEqualTo(Long value) {
            addCriterion("goods_id <>", value, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idGreaterThan(Long value) {
            addCriterion("goods_id >", value, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idGreaterThanOrEqualTo(Long value) {
            addCriterion("goods_id >=", value, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idLessThan(Long value) {
            addCriterion("goods_id <", value, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idLessThanOrEqualTo(Long value) {
            addCriterion("goods_id <=", value, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idIn(List<Long> values) {
            addCriterion("goods_id in", values, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idNotIn(List<Long> values) {
            addCriterion("goods_id not in", values, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idBetween(Long value1, Long value2) {
            addCriterion("goods_id between", value1, value2, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idNotBetween(Long value1, Long value2) {
            addCriterion("goods_id not between", value1, value2, "goods_id");
            return (Criteria) this;
        }

        public Criteria andAuthor_idIsNull() {
            addCriterion("author_id is null");
            return (Criteria) this;
        }

        public Criteria andAuthor_idIsNotNull() {
            addCriterion("author_id is not null");
            return (Criteria) this;
        }

        public Criteria andAuthor_idEqualTo(String value) {
            addCriterion("author_id =", value, "author_id");
            return (Criteria) this;
        }

        public Criteria andAuthor_idNotEqualTo(String value) {
            addCriterion("author_id <>", value, "author_id");
            return (Criteria) this;
        }

        public Criteria andAuthor_idGreaterThan(String value) {
            addCriterion("author_id >", value, "author_id");
            return (Criteria) this;
        }

        public Criteria andAuthor_idGreaterThanOrEqualTo(String value) {
            addCriterion("author_id >=", value, "author_id");
            return (Criteria) this;
        }

        public Criteria andAuthor_idLessThan(String value) {
            addCriterion("author_id <", value, "author_id");
            return (Criteria) this;
        }

        public Criteria andAuthor_idLessThanOrEqualTo(String value) {
            addCriterion("author_id <=", value, "author_id");
            return (Criteria) this;
        }

        public Criteria andAuthor_idLike(String value) {
            addCriterion("author_id like", value, "author_id");
            return (Criteria) this;
        }

        public Criteria andAuthor_idNotLike(String value) {
            addCriterion("author_id not like", value, "author_id");
            return (Criteria) this;
        }

        public Criteria andAuthor_idIn(List<String> values) {
            addCriterion("author_id in", values, "author_id");
            return (Criteria) this;
        }

        public Criteria andAuthor_idNotIn(List<String> values) {
            addCriterion("author_id not in", values, "author_id");
            return (Criteria) this;
        }

        public Criteria andAuthor_idBetween(String value1, String value2) {
            addCriterion("author_id between", value1, value2, "author_id");
            return (Criteria) this;
        }

        public Criteria andAuthor_idNotBetween(String value1, String value2) {
            addCriterion("author_id not between", value1, value2, "author_id");
            return (Criteria) this;
        }

        public Criteria andGoods_picIsNull() {
            addCriterion("goods_pic is null");
            return (Criteria) this;
        }

        public Criteria andGoods_picIsNotNull() {
            addCriterion("goods_pic is not null");
            return (Criteria) this;
        }

        public Criteria andGoods_picEqualTo(String value) {
            addCriterion("goods_pic =", value, "goods_pic");
            return (Criteria) this;
        }

        public Criteria andGoods_picNotEqualTo(String value) {
            addCriterion("goods_pic <>", value, "goods_pic");
            return (Criteria) this;
        }

        public Criteria andGoods_picGreaterThan(String value) {
            addCriterion("goods_pic >", value, "goods_pic");
            return (Criteria) this;
        }

        public Criteria andGoods_picGreaterThanOrEqualTo(String value) {
            addCriterion("goods_pic >=", value, "goods_pic");
            return (Criteria) this;
        }

        public Criteria andGoods_picLessThan(String value) {
            addCriterion("goods_pic <", value, "goods_pic");
            return (Criteria) this;
        }

        public Criteria andGoods_picLessThanOrEqualTo(String value) {
            addCriterion("goods_pic <=", value, "goods_pic");
            return (Criteria) this;
        }

        public Criteria andGoods_picLike(String value) {
            addCriterion("goods_pic like", value, "goods_pic");
            return (Criteria) this;
        }

        public Criteria andGoods_picNotLike(String value) {
            addCriterion("goods_pic not like", value, "goods_pic");
            return (Criteria) this;
        }

        public Criteria andGoods_picIn(List<String> values) {
            addCriterion("goods_pic in", values, "goods_pic");
            return (Criteria) this;
        }

        public Criteria andGoods_picNotIn(List<String> values) {
            addCriterion("goods_pic not in", values, "goods_pic");
            return (Criteria) this;
        }

        public Criteria andGoods_picBetween(String value1, String value2) {
            addCriterion("goods_pic between", value1, value2, "goods_pic");
            return (Criteria) this;
        }

        public Criteria andGoods_picNotBetween(String value1, String value2) {
            addCriterion("goods_pic not between", value1, value2, "goods_pic");
            return (Criteria) this;
        }

        public Criteria andHas_likedIsNull() {
            addCriterion("has_liked is null");
            return (Criteria) this;
        }

        public Criteria andHas_likedIsNotNull() {
            addCriterion("has_liked is not null");
            return (Criteria) this;
        }

        public Criteria andHas_likedEqualTo(Integer value) {
            addCriterion("has_liked =", value, "has_liked");
            return (Criteria) this;
        }

        public Criteria andHas_likedNotEqualTo(Integer value) {
            addCriterion("has_liked <>", value, "has_liked");
            return (Criteria) this;
        }

        public Criteria andHas_likedGreaterThan(Integer value) {
            addCriterion("has_liked >", value, "has_liked");
            return (Criteria) this;
        }

        public Criteria andHas_likedGreaterThanOrEqualTo(Integer value) {
            addCriterion("has_liked >=", value, "has_liked");
            return (Criteria) this;
        }

        public Criteria andHas_likedLessThan(Integer value) {
            addCriterion("has_liked <", value, "has_liked");
            return (Criteria) this;
        }

        public Criteria andHas_likedLessThanOrEqualTo(Integer value) {
            addCriterion("has_liked <=", value, "has_liked");
            return (Criteria) this;
        }

        public Criteria andHas_likedIn(List<Integer> values) {
            addCriterion("has_liked in", values, "has_liked");
            return (Criteria) this;
        }

        public Criteria andHas_likedNotIn(List<Integer> values) {
            addCriterion("has_liked not in", values, "has_liked");
            return (Criteria) this;
        }

        public Criteria andHas_likedBetween(Integer value1, Integer value2) {
            addCriterion("has_liked between", value1, value2, "has_liked");
            return (Criteria) this;
        }

        public Criteria andHas_likedNotBetween(Integer value1, Integer value2) {
            addCriterion("has_liked not between", value1, value2, "has_liked");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLike_numIsNull() {
            addCriterion("like_num is null");
            return (Criteria) this;
        }

        public Criteria andLike_numIsNotNull() {
            addCriterion("like_num is not null");
            return (Criteria) this;
        }

        public Criteria andLike_numEqualTo(Integer value) {
            addCriterion("like_num =", value, "like_num");
            return (Criteria) this;
        }

        public Criteria andLike_numNotEqualTo(Integer value) {
            addCriterion("like_num <>", value, "like_num");
            return (Criteria) this;
        }

        public Criteria andLike_numGreaterThan(Integer value) {
            addCriterion("like_num >", value, "like_num");
            return (Criteria) this;
        }

        public Criteria andLike_numGreaterThanOrEqualTo(Integer value) {
            addCriterion("like_num >=", value, "like_num");
            return (Criteria) this;
        }

        public Criteria andLike_numLessThan(Integer value) {
            addCriterion("like_num <", value, "like_num");
            return (Criteria) this;
        }

        public Criteria andLike_numLessThanOrEqualTo(Integer value) {
            addCriterion("like_num <=", value, "like_num");
            return (Criteria) this;
        }

        public Criteria andLike_numIn(List<Integer> values) {
            addCriterion("like_num in", values, "like_num");
            return (Criteria) this;
        }

        public Criteria andLike_numNotIn(List<Integer> values) {
            addCriterion("like_num not in", values, "like_num");
            return (Criteria) this;
        }

        public Criteria andLike_numBetween(Integer value1, Integer value2) {
            addCriterion("like_num between", value1, value2, "like_num");
            return (Criteria) this;
        }

        public Criteria andLike_numNotBetween(Integer value1, Integer value2) {
            addCriterion("like_num not between", value1, value2, "like_num");
            return (Criteria) this;
        }

        public Criteria andMark_wordIsNull() {
            addCriterion("mark_word is null");
            return (Criteria) this;
        }

        public Criteria andMark_wordIsNotNull() {
            addCriterion("mark_word is not null");
            return (Criteria) this;
        }

        public Criteria andMark_wordEqualTo(String value) {
            addCriterion("mark_word =", value, "mark_word");
            return (Criteria) this;
        }

        public Criteria andMark_wordNotEqualTo(String value) {
            addCriterion("mark_word <>", value, "mark_word");
            return (Criteria) this;
        }

        public Criteria andMark_wordGreaterThan(String value) {
            addCriterion("mark_word >", value, "mark_word");
            return (Criteria) this;
        }

        public Criteria andMark_wordGreaterThanOrEqualTo(String value) {
            addCriterion("mark_word >=", value, "mark_word");
            return (Criteria) this;
        }

        public Criteria andMark_wordLessThan(String value) {
            addCriterion("mark_word <", value, "mark_word");
            return (Criteria) this;
        }

        public Criteria andMark_wordLessThanOrEqualTo(String value) {
            addCriterion("mark_word <=", value, "mark_word");
            return (Criteria) this;
        }

        public Criteria andMark_wordLike(String value) {
            addCriterion("mark_word like", value, "mark_word");
            return (Criteria) this;
        }

        public Criteria andMark_wordNotLike(String value) {
            addCriterion("mark_word not like", value, "mark_word");
            return (Criteria) this;
        }

        public Criteria andMark_wordIn(List<String> values) {
            addCriterion("mark_word in", values, "mark_word");
            return (Criteria) this;
        }

        public Criteria andMark_wordNotIn(List<String> values) {
            addCriterion("mark_word not in", values, "mark_word");
            return (Criteria) this;
        }

        public Criteria andMark_wordBetween(String value1, String value2) {
            addCriterion("mark_word between", value1, value2, "mark_word");
            return (Criteria) this;
        }

        public Criteria andMark_wordNotBetween(String value1, String value2) {
            addCriterion("mark_word not between", value1, value2, "mark_word");
            return (Criteria) this;
        }

        public Criteria andModel_typeIsNull() {
            addCriterion("model_type is null");
            return (Criteria) this;
        }

        public Criteria andModel_typeIsNotNull() {
            addCriterion("model_type is not null");
            return (Criteria) this;
        }

        public Criteria andModel_typeEqualTo(String value) {
            addCriterion("model_type =", value, "model_type");
            return (Criteria) this;
        }

        public Criteria andModel_typeNotEqualTo(String value) {
            addCriterion("model_type <>", value, "model_type");
            return (Criteria) this;
        }

        public Criteria andModel_typeGreaterThan(String value) {
            addCriterion("model_type >", value, "model_type");
            return (Criteria) this;
        }

        public Criteria andModel_typeGreaterThanOrEqualTo(String value) {
            addCriterion("model_type >=", value, "model_type");
            return (Criteria) this;
        }

        public Criteria andModel_typeLessThan(String value) {
            addCriterion("model_type <", value, "model_type");
            return (Criteria) this;
        }

        public Criteria andModel_typeLessThanOrEqualTo(String value) {
            addCriterion("model_type <=", value, "model_type");
            return (Criteria) this;
        }

        public Criteria andModel_typeLike(String value) {
            addCriterion("model_type like", value, "model_type");
            return (Criteria) this;
        }

        public Criteria andModel_typeNotLike(String value) {
            addCriterion("model_type not like", value, "model_type");
            return (Criteria) this;
        }

        public Criteria andModel_typeIn(List<String> values) {
            addCriterion("model_type in", values, "model_type");
            return (Criteria) this;
        }

        public Criteria andModel_typeNotIn(List<String> values) {
            addCriterion("model_type not in", values, "model_type");
            return (Criteria) this;
        }

        public Criteria andModel_typeBetween(String value1, String value2) {
            addCriterion("model_type between", value1, value2, "model_type");
            return (Criteria) this;
        }

        public Criteria andModel_typeNotBetween(String value1, String value2) {
            addCriterion("model_type not between", value1, value2, "model_type");
            return (Criteria) this;
        }

        public Criteria andPage_viewIsNull() {
            addCriterion("page_view is null");
            return (Criteria) this;
        }

        public Criteria andPage_viewIsNotNull() {
            addCriterion("page_view is not null");
            return (Criteria) this;
        }

        public Criteria andPage_viewEqualTo(Integer value) {
            addCriterion("page_view =", value, "page_view");
            return (Criteria) this;
        }

        public Criteria andPage_viewNotEqualTo(Integer value) {
            addCriterion("page_view <>", value, "page_view");
            return (Criteria) this;
        }

        public Criteria andPage_viewGreaterThan(Integer value) {
            addCriterion("page_view >", value, "page_view");
            return (Criteria) this;
        }

        public Criteria andPage_viewGreaterThanOrEqualTo(Integer value) {
            addCriterion("page_view >=", value, "page_view");
            return (Criteria) this;
        }

        public Criteria andPage_viewLessThan(Integer value) {
            addCriterion("page_view <", value, "page_view");
            return (Criteria) this;
        }

        public Criteria andPage_viewLessThanOrEqualTo(Integer value) {
            addCriterion("page_view <=", value, "page_view");
            return (Criteria) this;
        }

        public Criteria andPage_viewIn(List<Integer> values) {
            addCriterion("page_view in", values, "page_view");
            return (Criteria) this;
        }

        public Criteria andPage_viewNotIn(List<Integer> values) {
            addCriterion("page_view not in", values, "page_view");
            return (Criteria) this;
        }

        public Criteria andPage_viewBetween(Integer value1, Integer value2) {
            addCriterion("page_view between", value1, value2, "page_view");
            return (Criteria) this;
        }

        public Criteria andPage_viewNotBetween(Integer value1, Integer value2) {
            addCriterion("page_view not between", value1, value2, "page_view");
            return (Criteria) this;
        }

        public Criteria andPositionIsNull() {
            addCriterion("position is null");
            return (Criteria) this;
        }

        public Criteria andPositionIsNotNull() {
            addCriterion("position is not null");
            return (Criteria) this;
        }

        public Criteria andPositionEqualTo(Integer value) {
            addCriterion("position =", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotEqualTo(Integer value) {
            addCriterion("position <>", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionGreaterThan(Integer value) {
            addCriterion("position >", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionGreaterThanOrEqualTo(Integer value) {
            addCriterion("position >=", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLessThan(Integer value) {
            addCriterion("position <", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLessThanOrEqualTo(Integer value) {
            addCriterion("position <=", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionIn(List<Integer> values) {
            addCriterion("position in", values, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotIn(List<Integer> values) {
            addCriterion("position not in", values, "position");
            return (Criteria) this;
        }

        public Criteria andPositionBetween(Integer value1, Integer value2) {
            addCriterion("position between", value1, value2, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotBetween(Integer value1, Integer value2) {
            addCriterion("position not between", value1, value2, "position");
            return (Criteria) this;
        }

        public Criteria andPublish_timeIsNull() {
            addCriterion("publish_time is null");
            return (Criteria) this;
        }

        public Criteria andPublish_timeIsNotNull() {
            addCriterion("publish_time is not null");
            return (Criteria) this;
        }

        public Criteria andPublish_timeEqualTo(Date value) {
            addCriterion("publish_time =", value, "publish_time");
            return (Criteria) this;
        }

        public Criteria andPublish_timeNotEqualTo(Date value) {
            addCriterion("publish_time <>", value, "publish_time");
            return (Criteria) this;
        }

        public Criteria andPublish_timeGreaterThan(Date value) {
            addCriterion("publish_time >", value, "publish_time");
            return (Criteria) this;
        }

        public Criteria andPublish_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("publish_time >=", value, "publish_time");
            return (Criteria) this;
        }

        public Criteria andPublish_timeLessThan(Date value) {
            addCriterion("publish_time <", value, "publish_time");
            return (Criteria) this;
        }

        public Criteria andPublish_timeLessThanOrEqualTo(Date value) {
            addCriterion("publish_time <=", value, "publish_time");
            return (Criteria) this;
        }

        public Criteria andPublish_timeIn(List<Date> values) {
            addCriterion("publish_time in", values, "publish_time");
            return (Criteria) this;
        }

        public Criteria andPublish_timeNotIn(List<Date> values) {
            addCriterion("publish_time not in", values, "publish_time");
            return (Criteria) this;
        }

        public Criteria andPublish_timeBetween(Date value1, Date value2) {
            addCriterion("publish_time between", value1, value2, "publish_time");
            return (Criteria) this;
        }

        public Criteria andPublish_timeNotBetween(Date value1, Date value2) {
            addCriterion("publish_time not between", value1, value2, "publish_time");
            return (Criteria) this;
        }

        public Criteria andRecommend_reasonIsNull() {
            addCriterion("recommend_reason is null");
            return (Criteria) this;
        }

        public Criteria andRecommend_reasonIsNotNull() {
            addCriterion("recommend_reason is not null");
            return (Criteria) this;
        }

        public Criteria andRecommend_reasonEqualTo(String value) {
            addCriterion("recommend_reason =", value, "recommend_reason");
            return (Criteria) this;
        }

        public Criteria andRecommend_reasonNotEqualTo(String value) {
            addCriterion("recommend_reason <>", value, "recommend_reason");
            return (Criteria) this;
        }

        public Criteria andRecommend_reasonGreaterThan(String value) {
            addCriterion("recommend_reason >", value, "recommend_reason");
            return (Criteria) this;
        }

        public Criteria andRecommend_reasonGreaterThanOrEqualTo(String value) {
            addCriterion("recommend_reason >=", value, "recommend_reason");
            return (Criteria) this;
        }

        public Criteria andRecommend_reasonLessThan(String value) {
            addCriterion("recommend_reason <", value, "recommend_reason");
            return (Criteria) this;
        }

        public Criteria andRecommend_reasonLessThanOrEqualTo(String value) {
            addCriterion("recommend_reason <=", value, "recommend_reason");
            return (Criteria) this;
        }

        public Criteria andRecommend_reasonLike(String value) {
            addCriterion("recommend_reason like", value, "recommend_reason");
            return (Criteria) this;
        }

        public Criteria andRecommend_reasonNotLike(String value) {
            addCriterion("recommend_reason not like", value, "recommend_reason");
            return (Criteria) this;
        }

        public Criteria andRecommend_reasonIn(List<String> values) {
            addCriterion("recommend_reason in", values, "recommend_reason");
            return (Criteria) this;
        }

        public Criteria andRecommend_reasonNotIn(List<String> values) {
            addCriterion("recommend_reason not in", values, "recommend_reason");
            return (Criteria) this;
        }

        public Criteria andRecommend_reasonBetween(String value1, String value2) {
            addCriterion("recommend_reason between", value1, value2, "recommend_reason");
            return (Criteria) this;
        }

        public Criteria andRecommend_reasonNotBetween(String value1, String value2) {
            addCriterion("recommend_reason not between", value1, value2, "recommend_reason");
            return (Criteria) this;
        }

        public Criteria andRecommend_themeIsNull() {
            addCriterion("recommend_theme is null");
            return (Criteria) this;
        }

        public Criteria andRecommend_themeIsNotNull() {
            addCriterion("recommend_theme is not null");
            return (Criteria) this;
        }

        public Criteria andRecommend_themeEqualTo(String value) {
            addCriterion("recommend_theme =", value, "recommend_theme");
            return (Criteria) this;
        }

        public Criteria andRecommend_themeNotEqualTo(String value) {
            addCriterion("recommend_theme <>", value, "recommend_theme");
            return (Criteria) this;
        }

        public Criteria andRecommend_themeGreaterThan(String value) {
            addCriterion("recommend_theme >", value, "recommend_theme");
            return (Criteria) this;
        }

        public Criteria andRecommend_themeGreaterThanOrEqualTo(String value) {
            addCriterion("recommend_theme >=", value, "recommend_theme");
            return (Criteria) this;
        }

        public Criteria andRecommend_themeLessThan(String value) {
            addCriterion("recommend_theme <", value, "recommend_theme");
            return (Criteria) this;
        }

        public Criteria andRecommend_themeLessThanOrEqualTo(String value) {
            addCriterion("recommend_theme <=", value, "recommend_theme");
            return (Criteria) this;
        }

        public Criteria andRecommend_themeLike(String value) {
            addCriterion("recommend_theme like", value, "recommend_theme");
            return (Criteria) this;
        }

        public Criteria andRecommend_themeNotLike(String value) {
            addCriterion("recommend_theme not like", value, "recommend_theme");
            return (Criteria) this;
        }

        public Criteria andRecommend_themeIn(List<String> values) {
            addCriterion("recommend_theme in", values, "recommend_theme");
            return (Criteria) this;
        }

        public Criteria andRecommend_themeNotIn(List<String> values) {
            addCriterion("recommend_theme not in", values, "recommend_theme");
            return (Criteria) this;
        }

        public Criteria andRecommend_themeBetween(String value1, String value2) {
            addCriterion("recommend_theme between", value1, value2, "recommend_theme");
            return (Criteria) this;
        }

        public Criteria andRecommend_themeNotBetween(String value1, String value2) {
            addCriterion("recommend_theme not between", value1, value2, "recommend_theme");
            return (Criteria) this;
        }

        public Criteria andShow_call_backIsNull() {
            addCriterion("show_call_back is null");
            return (Criteria) this;
        }

        public Criteria andShow_call_backIsNotNull() {
            addCriterion("show_call_back is not null");
            return (Criteria) this;
        }

        public Criteria andShow_call_backEqualTo(Integer value) {
            addCriterion("show_call_back =", value, "show_call_back");
            return (Criteria) this;
        }

        public Criteria andShow_call_backNotEqualTo(Integer value) {
            addCriterion("show_call_back <>", value, "show_call_back");
            return (Criteria) this;
        }

        public Criteria andShow_call_backGreaterThan(Integer value) {
            addCriterion("show_call_back >", value, "show_call_back");
            return (Criteria) this;
        }

        public Criteria andShow_call_backGreaterThanOrEqualTo(Integer value) {
            addCriterion("show_call_back >=", value, "show_call_back");
            return (Criteria) this;
        }

        public Criteria andShow_call_backLessThan(Integer value) {
            addCriterion("show_call_back <", value, "show_call_back");
            return (Criteria) this;
        }

        public Criteria andShow_call_backLessThanOrEqualTo(Integer value) {
            addCriterion("show_call_back <=", value, "show_call_back");
            return (Criteria) this;
        }

        public Criteria andShow_call_backIn(List<Integer> values) {
            addCriterion("show_call_back in", values, "show_call_back");
            return (Criteria) this;
        }

        public Criteria andShow_call_backNotIn(List<Integer> values) {
            addCriterion("show_call_back not in", values, "show_call_back");
            return (Criteria) this;
        }

        public Criteria andShow_call_backBetween(Integer value1, Integer value2) {
            addCriterion("show_call_back between", value1, value2, "show_call_back");
            return (Criteria) this;
        }

        public Criteria andShow_call_backNotBetween(Integer value1, Integer value2) {
            addCriterion("show_call_back not between", value1, value2, "show_call_back");
            return (Criteria) this;
        }

        public Criteria andSkuIsNull() {
            addCriterion("sku is null");
            return (Criteria) this;
        }

        public Criteria andSkuIsNotNull() {
            addCriterion("sku is not null");
            return (Criteria) this;
        }

        public Criteria andSkuEqualTo(String value) {
            addCriterion("sku =", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuNotEqualTo(String value) {
            addCriterion("sku <>", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuGreaterThan(String value) {
            addCriterion("sku >", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuGreaterThanOrEqualTo(String value) {
            addCriterion("sku >=", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuLessThan(String value) {
            addCriterion("sku <", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuLessThanOrEqualTo(String value) {
            addCriterion("sku <=", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuLike(String value) {
            addCriterion("sku like", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuNotLike(String value) {
            addCriterion("sku not like", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuIn(List<String> values) {
            addCriterion("sku in", values, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuNotIn(List<String> values) {
            addCriterion("sku not in", values, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuBetween(String value1, String value2) {
            addCriterion("sku between", value1, value2, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuNotBetween(String value1, String value2) {
            addCriterion("sku not between", value1, value2, "sku");
            return (Criteria) this;
        }

        public Criteria andSrvIsNull() {
            addCriterion("srv is null");
            return (Criteria) this;
        }

        public Criteria andSrvIsNotNull() {
            addCriterion("srv is not null");
            return (Criteria) this;
        }

        public Criteria andSrvEqualTo(String value) {
            addCriterion("srv =", value, "srv");
            return (Criteria) this;
        }

        public Criteria andSrvNotEqualTo(String value) {
            addCriterion("srv <>", value, "srv");
            return (Criteria) this;
        }

        public Criteria andSrvGreaterThan(String value) {
            addCriterion("srv >", value, "srv");
            return (Criteria) this;
        }

        public Criteria andSrvGreaterThanOrEqualTo(String value) {
            addCriterion("srv >=", value, "srv");
            return (Criteria) this;
        }

        public Criteria andSrvLessThan(String value) {
            addCriterion("srv <", value, "srv");
            return (Criteria) this;
        }

        public Criteria andSrvLessThanOrEqualTo(String value) {
            addCriterion("srv <=", value, "srv");
            return (Criteria) this;
        }

        public Criteria andSrvLike(String value) {
            addCriterion("srv like", value, "srv");
            return (Criteria) this;
        }

        public Criteria andSrvNotLike(String value) {
            addCriterion("srv not like", value, "srv");
            return (Criteria) this;
        }

        public Criteria andSrvIn(List<String> values) {
            addCriterion("srv in", values, "srv");
            return (Criteria) this;
        }

        public Criteria andSrvNotIn(List<String> values) {
            addCriterion("srv not in", values, "srv");
            return (Criteria) this;
        }

        public Criteria andSrvBetween(String value1, String value2) {
            addCriterion("srv between", value1, value2, "srv");
            return (Criteria) this;
        }

        public Criteria andSrvNotBetween(String value1, String value2) {
            addCriterion("srv not between", value1, value2, "srv");
            return (Criteria) this;
        }

        public Criteria andSub_positionIsNull() {
            addCriterion("sub_position is null");
            return (Criteria) this;
        }

        public Criteria andSub_positionIsNotNull() {
            addCriterion("sub_position is not null");
            return (Criteria) this;
        }

        public Criteria andSub_positionEqualTo(Integer value) {
            addCriterion("sub_position =", value, "sub_position");
            return (Criteria) this;
        }

        public Criteria andSub_positionNotEqualTo(Integer value) {
            addCriterion("sub_position <>", value, "sub_position");
            return (Criteria) this;
        }

        public Criteria andSub_positionGreaterThan(Integer value) {
            addCriterion("sub_position >", value, "sub_position");
            return (Criteria) this;
        }

        public Criteria andSub_positionGreaterThanOrEqualTo(Integer value) {
            addCriterion("sub_position >=", value, "sub_position");
            return (Criteria) this;
        }

        public Criteria andSub_positionLessThan(Integer value) {
            addCriterion("sub_position <", value, "sub_position");
            return (Criteria) this;
        }

        public Criteria andSub_positionLessThanOrEqualTo(Integer value) {
            addCriterion("sub_position <=", value, "sub_position");
            return (Criteria) this;
        }

        public Criteria andSub_positionIn(List<Integer> values) {
            addCriterion("sub_position in", values, "sub_position");
            return (Criteria) this;
        }

        public Criteria andSub_positionNotIn(List<Integer> values) {
            addCriterion("sub_position not in", values, "sub_position");
            return (Criteria) this;
        }

        public Criteria andSub_positionBetween(Integer value1, Integer value2) {
            addCriterion("sub_position between", value1, value2, "sub_position");
            return (Criteria) this;
        }

        public Criteria andSub_positionNotBetween(Integer value1, Integer value2) {
            addCriterion("sub_position not between", value1, value2, "sub_position");
            return (Criteria) this;
        }

        public Criteria andTagsIsNull() {
            addCriterion("tags is null");
            return (Criteria) this;
        }

        public Criteria andTagsIsNotNull() {
            addCriterion("tags is not null");
            return (Criteria) this;
        }

        public Criteria andTagsEqualTo(String value) {
            addCriterion("tags =", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotEqualTo(String value) {
            addCriterion("tags <>", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsGreaterThan(String value) {
            addCriterion("tags >", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsGreaterThanOrEqualTo(String value) {
            addCriterion("tags >=", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLessThan(String value) {
            addCriterion("tags <", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLessThanOrEqualTo(String value) {
            addCriterion("tags <=", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLike(String value) {
            addCriterion("tags like", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotLike(String value) {
            addCriterion("tags not like", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsIn(List<String> values) {
            addCriterion("tags in", values, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotIn(List<String> values) {
            addCriterion("tags not in", values, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsBetween(String value1, String value2) {
            addCriterion("tags between", value1, value2, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotBetween(String value1, String value2) {
            addCriterion("tags not between", value1, value2, "tags");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeEqualTo(Date value) {
            addCriterion("create_time =", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThan(Date value) {
            addCriterion("create_time >", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThan(Date value) {
            addCriterion("create_time <", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIn(List<Date> values) {
            addCriterion("create_time in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods
     *
     * @mbg.generated do_not_delete_during_merge Thu Mar 09 00:03:55 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}