package com.tkylin.jdfx.db.model;

import java.util.Date;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_id
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.author_id
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    private String authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_pic
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    private String goodsPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.has_liked
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    private Integer hasLiked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.like_num
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    private Integer likeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.mark_word
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    private String markWord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.model_type
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    private String modelType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.page_view
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    private Integer pageView;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.position
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    private Integer position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.publish_time
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    private Date publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.recommend_reason
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    private String recommendReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.recommend_theme
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    private String recommendTheme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.show_call_back
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    private Integer showCallBack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.sku
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    private String sku;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.sku_id
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    private String skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.srv
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    private String srv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.sub_position
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    private Integer subPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.tags
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.create_time
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.status
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_id
     *
     * @return the value of goods.goods_id
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_id
     *
     * @param goodsId the value for goods.goods_id
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.author_id
     *
     * @return the value of goods.author_id
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public String getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.author_id
     *
     * @param authorId the value for goods.author_id
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public void setAuthorId(String authorId) {
        this.authorId = authorId == null ? null : authorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_pic
     *
     * @return the value of goods.goods_pic
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public String getGoodsPic() {
        return goodsPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_pic
     *
     * @param goodsPic the value for goods.goods_pic
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public void setGoodsPic(String goodsPic) {
        this.goodsPic = goodsPic == null ? null : goodsPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.has_liked
     *
     * @return the value of goods.has_liked
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public Integer getHasLiked() {
        return hasLiked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.has_liked
     *
     * @param hasLiked the value for goods.has_liked
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public void setHasLiked(Integer hasLiked) {
        this.hasLiked = hasLiked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.like_num
     *
     * @return the value of goods.like_num
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public Integer getLikeNum() {
        return likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.like_num
     *
     * @param likeNum the value for goods.like_num
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public void setLikeNum(Integer likeNum) {
        this.likeNum = likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.mark_word
     *
     * @return the value of goods.mark_word
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public String getMarkWord() {
        return markWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.mark_word
     *
     * @param markWord the value for goods.mark_word
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public void setMarkWord(String markWord) {
        this.markWord = markWord == null ? null : markWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.model_type
     *
     * @return the value of goods.model_type
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public String getModelType() {
        return modelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.model_type
     *
     * @param modelType the value for goods.model_type
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public void setModelType(String modelType) {
        this.modelType = modelType == null ? null : modelType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.page_view
     *
     * @return the value of goods.page_view
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public Integer getPageView() {
        return pageView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.page_view
     *
     * @param pageView the value for goods.page_view
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public void setPageView(Integer pageView) {
        this.pageView = pageView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.position
     *
     * @return the value of goods.position
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.position
     *
     * @param position the value for goods.position
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.publish_time
     *
     * @return the value of goods.publish_time
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.publish_time
     *
     * @param publishTime the value for goods.publish_time
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.recommend_reason
     *
     * @return the value of goods.recommend_reason
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public String getRecommendReason() {
        return recommendReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.recommend_reason
     *
     * @param recommendReason the value for goods.recommend_reason
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public void setRecommendReason(String recommendReason) {
        this.recommendReason = recommendReason == null ? null : recommendReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.recommend_theme
     *
     * @return the value of goods.recommend_theme
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public String getRecommendTheme() {
        return recommendTheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.recommend_theme
     *
     * @param recommendTheme the value for goods.recommend_theme
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public void setRecommendTheme(String recommendTheme) {
        this.recommendTheme = recommendTheme == null ? null : recommendTheme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.show_call_back
     *
     * @return the value of goods.show_call_back
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public Integer getShowCallBack() {
        return showCallBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.show_call_back
     *
     * @param showCallBack the value for goods.show_call_back
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public void setShowCallBack(Integer showCallBack) {
        this.showCallBack = showCallBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.sku
     *
     * @return the value of goods.sku
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public String getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.sku
     *
     * @param sku the value for goods.sku
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.sku_id
     *
     * @return the value of goods.sku_id
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public String getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.sku_id
     *
     * @param skuId the value for goods.sku_id
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public void setSkuId(String skuId) {
        this.skuId = skuId == null ? null : skuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.srv
     *
     * @return the value of goods.srv
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public String getSrv() {
        return srv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.srv
     *
     * @param srv the value for goods.srv
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public void setSrv(String srv) {
        this.srv = srv == null ? null : srv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.sub_position
     *
     * @return the value of goods.sub_position
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public Integer getSubPosition() {
        return subPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.sub_position
     *
     * @param subPosition the value for goods.sub_position
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public void setSubPosition(Integer subPosition) {
        this.subPosition = subPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.tags
     *
     * @return the value of goods.tags
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.tags
     *
     * @param tags the value for goods.tags
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.create_time
     *
     * @return the value of goods.create_time
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.create_time
     *
     * @param createTime the value for goods.create_time
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.status
     *
     * @return the value of goods.status
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.status
     *
     * @param status the value for goods.status
     *
     * @mbg.generated Mon Mar 20 17:44:40 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}