package com.tkylin.jdfx.db.model;

import java.util.Date;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_id
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    private Long goods_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.author_id
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    private String author_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_pic
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    private String goods_pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.has_liked
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    private Integer has_liked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.like_num
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    private Integer like_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.mark_word
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    private String mark_word;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.model_type
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    private String model_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.page_view
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    private Integer page_view;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.position
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    private Integer position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.publish_time
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    private Date publish_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.recommend_reason
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    private String recommend_reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.recommend_theme
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    private String recommend_theme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.show_call_back
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    private Integer show_call_back;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.sku
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    private String sku;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.srv
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    private String srv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.sub_position
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    private Integer sub_position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.tags
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.create_time
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.status
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_id
     *
     * @return the value of goods.goods_id
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public Long getGoods_id() {
        return goods_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_id
     *
     * @param goods_id the value for goods.goods_id
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public void setGoods_id(Long goods_id) {
        this.goods_id = goods_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.author_id
     *
     * @return the value of goods.author_id
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public String getAuthor_id() {
        return author_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.author_id
     *
     * @param author_id the value for goods.author_id
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public void setAuthor_id(String author_id) {
        this.author_id = author_id == null ? null : author_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_pic
     *
     * @return the value of goods.goods_pic
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public String getGoods_pic() {
        return goods_pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_pic
     *
     * @param goods_pic the value for goods.goods_pic
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public void setGoods_pic(String goods_pic) {
        this.goods_pic = goods_pic == null ? null : goods_pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.has_liked
     *
     * @return the value of goods.has_liked
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public Integer getHas_liked() {
        return has_liked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.has_liked
     *
     * @param has_liked the value for goods.has_liked
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public void setHas_liked(Integer has_liked) {
        this.has_liked = has_liked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.like_num
     *
     * @return the value of goods.like_num
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public Integer getLike_num() {
        return like_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.like_num
     *
     * @param like_num the value for goods.like_num
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public void setLike_num(Integer like_num) {
        this.like_num = like_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.mark_word
     *
     * @return the value of goods.mark_word
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public String getMark_word() {
        return mark_word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.mark_word
     *
     * @param mark_word the value for goods.mark_word
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public void setMark_word(String mark_word) {
        this.mark_word = mark_word == null ? null : mark_word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.model_type
     *
     * @return the value of goods.model_type
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public String getModel_type() {
        return model_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.model_type
     *
     * @param model_type the value for goods.model_type
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public void setModel_type(String model_type) {
        this.model_type = model_type == null ? null : model_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.page_view
     *
     * @return the value of goods.page_view
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public Integer getPage_view() {
        return page_view;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.page_view
     *
     * @param page_view the value for goods.page_view
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public void setPage_view(Integer page_view) {
        this.page_view = page_view;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.position
     *
     * @return the value of goods.position
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.position
     *
     * @param position the value for goods.position
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.publish_time
     *
     * @return the value of goods.publish_time
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public Date getPublish_time() {
        return publish_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.publish_time
     *
     * @param publish_time the value for goods.publish_time
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public void setPublish_time(Date publish_time) {
        this.publish_time = publish_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.recommend_reason
     *
     * @return the value of goods.recommend_reason
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public String getRecommend_reason() {
        return recommend_reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.recommend_reason
     *
     * @param recommend_reason the value for goods.recommend_reason
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public void setRecommend_reason(String recommend_reason) {
        this.recommend_reason = recommend_reason == null ? null : recommend_reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.recommend_theme
     *
     * @return the value of goods.recommend_theme
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public String getRecommend_theme() {
        return recommend_theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.recommend_theme
     *
     * @param recommend_theme the value for goods.recommend_theme
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public void setRecommend_theme(String recommend_theme) {
        this.recommend_theme = recommend_theme == null ? null : recommend_theme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.show_call_back
     *
     * @return the value of goods.show_call_back
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public Integer getShow_call_back() {
        return show_call_back;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.show_call_back
     *
     * @param show_call_back the value for goods.show_call_back
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public void setShow_call_back(Integer show_call_back) {
        this.show_call_back = show_call_back;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.sku
     *
     * @return the value of goods.sku
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public String getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.sku
     *
     * @param sku the value for goods.sku
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.srv
     *
     * @return the value of goods.srv
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public String getSrv() {
        return srv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.srv
     *
     * @param srv the value for goods.srv
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public void setSrv(String srv) {
        this.srv = srv == null ? null : srv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.sub_position
     *
     * @return the value of goods.sub_position
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public Integer getSub_position() {
        return sub_position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.sub_position
     *
     * @param sub_position the value for goods.sub_position
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public void setSub_position(Integer sub_position) {
        this.sub_position = sub_position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.tags
     *
     * @return the value of goods.tags
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.tags
     *
     * @param tags the value for goods.tags
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.create_time
     *
     * @return the value of goods.create_time
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.create_time
     *
     * @param create_time the value for goods.create_time
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.status
     *
     * @return the value of goods.status
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.status
     *
     * @param status the value for goods.status
     *
     * @mbg.generated Thu Mar 09 00:03:55 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}