CREATE TABLE `goods` (
  `goods_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `author_id` VARCHAR(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '作者id',
  `goods_pic` VARCHAR(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '主图',
  `has_liked` INT(11) DEFAULT NULL COMMENT '是否有点赞数',
  `id` VARCHAR(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '发现id',
  `like_num` INT(11) DEFAULT NULL COMMENT '喜欢数',
  `mark_word` VARCHAR(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '标签词',
  `model_type` VARCHAR(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '类型',
  `page_view` INT(11) DEFAULT NULL COMMENT '阅读数',
  `position` INT(11) DEFAULT NULL,
  `publish_time` DATETIME DEFAULT NULL COMMENT '发布时间',
  `recommend_reason` VARCHAR(600) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '推荐理由',
  `recommend_theme` VARCHAR(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '推荐主题',
  `show_call_back` INT(11) DEFAULT NULL,
  `sku` VARCHAR(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'sku',
  `srv` VARCHAR(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sub_position` INT(11) DEFAULT NULL,
  `tags` VARCHAR(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `status` INT(11) DEFAULT '1',
  PRIMARY KEY (`goods_id`),
  UNIQUE KEY `IDX_sku` (`sku`)
);