package com.tkylin.jdfx.db.dao;

import com.tkylin.jdfx.db.model.ArticleType;
import com.tkylin.jdfx.db.model.ArticleTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    long countByExample(ArticleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    int deleteByExample(ArticleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    int insert(ArticleType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    int insertSelective(ArticleType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    List<ArticleType> selectByExample(ArticleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    ArticleType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    int updateByExampleSelective(@Param("record") ArticleType record, @Param("example") ArticleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    int updateByExample(@Param("record") ArticleType record, @Param("example") ArticleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    int updateByPrimaryKeySelective(ArticleType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    int updateByPrimaryKey(ArticleType record);
}