package com.tkylin.jdfx.db.dao;

import com.tkylin.jdfx.db.model.Find;
import com.tkylin.jdfx.db.model.FindExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    long countByExample(FindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    int deleteByExample(FindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    int deleteByPrimaryKey(Long findId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    int insert(Find record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    int insertSelective(Find record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    List<Find> selectByExample(FindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    Find selectByPrimaryKey(Long findId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    int updateByExampleSelective(@Param("record") Find record, @Param("example") FindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    int updateByExample(@Param("record") Find record, @Param("example") FindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    int updateByPrimaryKeySelective(Find record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find
     *
     * @mbg.generated Fri Mar 17 16:42:45 CST 2017
     */
    int updateByPrimaryKey(Find record);
}